#!/usr/bin/env python3
"""Generate the Phase-1 LCD bring-up test pattern as an LVGL 9 RGB565 image.

The pattern is deliberately geometric so that a single glance at the panel
tells us four things:

  * the eight colour bars      -> colour order (is red really red, no R/B swap)
  * the exact 24x24 square     -> aspect ratio (a square must look square)
  * the 1 px black separator   -> horizontal line rendering / no row doubling
  * the 96x72 outline          -> image edges land on the right pixels

Run from the project root:

    python tools/gen_test_pattern.py

Outputs (both regenerated in place):
    main/ui/assets/test_pattern.c
    main/ui/assets/test_pattern.h
"""

from pathlib import Path

W = 96
H = 72
BAR_H = 36          # height of the colour-bar region (top)
SEP_ROW = 34        # first row of the 2 px black separator
SQ = 24             # edge length of the aspect-ratio square
SQ_X = (W - SQ) // 2
SQ_Y = 42

WHITE = 0xFFFF
YELLOW = 0xFFE0
CYAN = 0x07FF
GREEN = 0x07E0
MAGENTA = 0xF81F
RED = 0xF800
BLUE = 0x001F
BLACK = 0x0000
GRAY = 0x3186       # r = g = b = 48  -> 5-6-5 packed

BARS = [WHITE, YELLOW, CYAN, GREEN, MAGENTA, RED, BLUE, BLACK]


def pixel(x: int, y: int) -> int:
    if y < SEP_ROW:
        return BARS[(x * len(BARS)) // W]
    if y < BAR_H:
        return BLACK
    if SQ_X <= x < SQ_X + SQ and SQ_Y <= y < SQ_Y + SQ:
        return WHITE
    return GRAY


def main() -> None:
    out_dir = Path(__file__).resolve().parent.parent / "main" / "ui" / "assets"
    out_dir.mkdir(parents=True, exist_ok=True)

    values = [pixel(x, y) for y in range(H) for x in range(W)]

    lines = []
    for i in range(0, len(values), 12):
        chunk = values[i:i + 12]
        lines.append("    " + " ".join(f"0x{v:04X}," for v in chunk))

    c_src = f"""/* AUTO-GENERATED by tools/gen_test_pattern.py -- do not edit by hand. */
#include "test_pattern.h"

/* {W}x{H} RGB565 test pattern: 8 colour bars + aspect-ratio square. */
static const uint16_t test_pattern_map[] = {{
{chr(10).join(lines)}
}};

const lv_image_dsc_t test_pattern = {{
    .header = {{
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565,
        .flags = 0,
        .w = {W},
        .h = {H},
        .stride = {W} * 2,
    }},
    .data_size = sizeof(test_pattern_map),
    .data = (const uint8_t *)test_pattern_map,
}};
"""

    h_src = f"""/* AUTO-GENERATED by tools/gen_test_pattern.py -- do not edit by hand. */
#pragma once

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {{
#endif

/* {W}x{H} RGB565 LCD bring-up test pattern (colour bars + aspect square). */
extern const lv_image_dsc_t test_pattern;

#ifdef __cplusplus
}}
#endif
"""

    (out_dir / "test_pattern.c").write_text(c_src, encoding="utf-8", newline="\n")
    (out_dir / "test_pattern.h").write_text(h_src, encoding="utf-8", newline="\n")

    print(f"wrote {W}x{H} RGB565 pattern "
          f"({len(values) * 2} bytes) to {out_dir}")


if __name__ == "__main__":
    main()
