#!/usr/bin/env python3
"""Generate full-cell 1bpp ASCII bitmap fonts (16/24/32 px) for the reader.

WHY
---
The card's GBK faces cover only the double-byte CJK area (23940 glyphs, no
ASCII), so when the reader draws a mixed CN/EN document the Latin characters
fall through to the font's fallback.  The previous fallback was the embedded
16 px CJK face, which left Latin at 16 px next to 32 px Han - half the size,
and `lv_draw_label.c` positions every glyph by the *line* font's metrics while
taking the glyph's own box, so the small Latin also sank toward the baseline.

The fix is a fallback that is the SAME height, baseline and cell width as the
Han around it: a full-cell 1bpp bitmap of ASCII rendered to fill the N x N cell.
This file emits exactly that, in the on-card GBK face's byte layout so the same
column-major decode path in ui/sd_font.cpp serves both:

    byte index = x*(N/8) + (y>>3)
    MSB-first within the byte: bit (7 - (y & 7)) is pixel (x, y)

USAGE
-----
    python tools/gen_ascii_font.py
Emits main/ui/ascii_fonts.c and main/ui/ascii_fonts.h (do not edit by hand).
"""
import os
import sys

from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
TTF = os.path.join(REPO, "managed_components", "lvgl__lvgl", "scripts",
                   "built_in_font", "Montserrat-Medium.ttf")
SIZES = (16, 24, 32)
PAD = 2  # px of vertical/horizontal breathing room inside the cell
OUT_C = os.path.join(REPO, "main", "ui", "ascii_fonts.cpp")
OUT_H = os.path.join(REPO, "main", "ui", "ascii_fonts.h")


def render_glyph(ch, cell):
    """Render one ASCII char as a full-cell 1bpp PIL image."""
    # Render large, crop to tight bbox, then scale to fill the cell height
    # (minus PAD) while preserving aspect, capped so it never overflows.
    big = 256
    font = ImageFont.truetype(TTF, big)
    canvas = Image.new("L", (big * 2, big * 2), 0)
    ImageDraw.Draw(canvas).text((big // 4, big // 4), ch, fill=255, font=font)
    bbox = canvas.getbbox()
    if bbox is None:
        return Image.new("L", (cell, cell), 0)
    glyph = canvas.crop(bbox)
    gw, gh = glyph.size
    target = cell - 2 * PAD
    scale = min(target / gh, target / gw)
    nw, nh = max(1, round(gw * scale)), max(1, round(gh * scale))
    glyph = glyph.resize((nw, nh), Image.LANCZOS)
    out = Image.new("L", (cell, cell), 0)
    out.paste(glyph, ((cell - nw) // 2, (cell - nh) // 2))
    return out


def to_bytes(img, cell):
    """Column-major 1bpp, MSB-first vertical (matches the GBK decode path)."""
    bpr = cell // 8
    data = bytearray(cell * bpr)
    px = img.load()
    for x in range(cell):
        for y in range(cell):
            if px[x, y] >= 128:
                byte = x * bpr + (y >> 3)
                data[byte] |= 1 << (7 - (y & 7))
    return bytes(data)


def main():
    if not os.path.exists(TTF):
        sys.exit("TTF not found: %s" % TTF)

    tables = {}
    for cell in SIZES:
        buf = bytearray()
        for cp in range(0x20, 0x7F):  # 95 slots, slot = cp - 0x20
            buf += to_bytes(render_glyph(chr(cp), cell), cell)
        tables[cell] = bytes(buf)

    # ---- header ----
    h_lines = [
        "/* ascii_fonts.h - GENERATED by tools/gen_ascii_font.py. Do not edit. */",
        "#pragma once",
        "#include <stdint.h>",
        "namespace ui {",
    ]
    for cell in SIZES:
        h_lines.append("extern const uint8_t ascii%d_glyphs[];" % cell)
    h_lines.append("}  // namespace ui")

    # ---- source ----
    c_lines = [
        "/* ascii_fonts.c - GENERATED by tools/gen_ascii_font.py. Do not edit. */",
        "/*",
        " * Full-cell 1bpp ASCII bitmaps (column-major, MSB-first vertical),",
        " * one N x N cell per glyph, slot = codepoint - 0x20 (95 glyphs).",
        " * Shared by ui/sd_font.cpp as the size-matched Latin fallback for the",
        " * GBK reading faces so English is the same height as the Han around it.",
        " */",
        '#include "ascii_fonts.h"',
        "",
        "namespace ui {",
    ]
    for cell in SIZES:
        glyph_bytes = cell * cell // 8
        total = 95 * glyph_bytes
        c_lines.append("extern const uint8_t ascii%d_glyphs[%d] = {" % (cell, total))
        data = tables[cell]
        row = ""
        for i, b in enumerate(data):
            token = "0x%02X," % b
            if len(row) + len(token) > 96:
                c_lines.append("    " + row)
                row = ""
            row += token
        if row:
            c_lines.append("    " + row)
        c_lines.append("};")
        c_lines.append("")
    c_lines.append("}  // namespace ui")

    with open(OUT_H, "w", encoding="ascii") as f:
        f.write("\n".join(h_lines) + "\n")
    with open(OUT_C, "w", encoding="ascii") as f:
        f.write("\n".join(c_lines) + "\n")

    for cell in SIZES:
        print("ascii%d: %d glyphs, %d bytes" % (cell, 95, len(tables[cell])))


if __name__ == "__main__":
    main()
