/* Auto-generated by tools/gen_model.py - do not edit. */
#ifndef __PD_MODEL_DATA_H
#define __PD_MODEL_DATA_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define PD_LAYER_DEPTHWISE   0
#define PD_LAYER_CONV        1

#define PD_INPUT_W           96
#define PD_INPUT_H           96
#define PD_INPUT_C           1
#define PD_INPUT_ZP          (-1)
#define PD_NUM_LAYERS        28
#define PD_FEATURE_H         3
#define PD_FEATURE_W         3
#define PD_FEATURE_C         256
#define PD_FEATURE_ZP        (-128)
#define PD_LOGIT_SCALE       (0.01251875143f)
#define PD_LOGIT_ZP          (-1)
#define PD_TENSOR_ARENA_SIZE 36864
#define PD_SCRATCH_SIZE      4672

typedef struct {
    uint8_t        type;
    uint8_t        ch_mult;
    uint8_t        kernel;
    uint8_t        stride;
    uint8_t        pad;
    int16_t        in_h, in_w, in_c;
    int16_t        out_h, out_w, out_c;
    int32_t        input_offset;
    int32_t        output_offset;
    int32_t        act_min, act_max;
    const int8_t  *weights;
    const int32_t *bias;
    const int32_t *multiplier;
    const int32_t *shift;
} pd_layer_t;

extern const pd_layer_t pd_layers[PD_NUM_LAYERS];
extern const int16_t pd_cam_w[PD_FEATURE_C];

#ifdef __cplusplus
}
#endif
#endif
