manifest:
  remotes:
    - name: zephyr
      url-base: https://github.com/zephyrproject-rtos
  defaults:
    remote: zephyr
  self:
    path: .
  projects:
    - name: zephyr
      path: zephyr/zephyr
      west-commands: scripts/west-commands.yml
    - name: hal_stm32
      path: zephyr/modules/hal/stm32
    - name: cmsis
      path: zephyr/modules/hal/cmsis
    - name: fatfs
      path: zephyr/modules/fs/fatfs
    - name: lvgl
      path: zephyr/modules/lib/gui/lvgl
