/*
 * web_server.c
 *
 * HTTP configuration server handlers.
 */
#include "web_server.h"

#include <stdlib.h>
#include <string.h>
#include "esp_log.h"
#include "esp_system.h"
#include "esp_http_server.h"

#include "config_manager.h"
#include "wifi_manager.h"
#include "web_ui.h"
#include "system_manager.h"

static const char *TAG = "web";
static httpd_handle_t s_server = NULL;

/* Symbol names generated by EMBED_FILES "web/index.html" in CMakeLists.txt. */
extern const uint8_t web_index_html_start[];
extern const uint8_t web_index_html_end[];

static esp_err_t root_handler(httpd_req_t *req)
{
    size_t len = (size_t)(web_index_html_end - web_index_html_start);
    httpd_resp_set_type(req, "text/html; charset=utf-8");
    return httpd_resp_send(req, (const char *)web_index_html_start, (int)len);
}

static esp_err_t status_handler(httpd_req_t *req)
{
    char *json = web_ui_build_status_json();
    if (json == NULL) {
        return httpd_resp_send_500(req);
    }
    httpd_resp_set_type(req, "application/json");
    httpd_resp_send(req, json, (int)strlen(json));
    free(json);
    return ESP_OK;
}

static esp_err_t scan_handler(httpd_req_t *req)
{
    uint16_t max = 32;
    wifi_ap_record_t *aps = calloc(max, sizeof(wifi_ap_record_t));
    if (aps == NULL) {
        return httpd_resp_send_500(req);
    }
    esp_err_t err = wifi_manager_scan(aps, &max);
    if (err != ESP_OK) {
        free(aps);
        return httpd_resp_send_500(req);
    }
    char *json = web_ui_build_scan_json(aps, max);
    free(aps);
    if (json == NULL) {
        return httpd_resp_send_500(req);
    }
    httpd_resp_set_type(req, "application/json");
    httpd_resp_send(req, json, (int)strlen(json));
    free(json);
    return ESP_OK;
}

static esp_err_t connect_handler(httpd_req_t *req)
{
    char query[256];
    char ssid[CFG_SSID_MAX_LEN + 1] = {0};
    char password[CFG_PASSWORD_MAX_LEN + 1] = {0};

    if (httpd_req_get_url_query_str(req, query, sizeof(query)) != ESP_OK) {
        return httpd_resp_send_500(req);
    }
    httpd_query_key_value(query, "ssid", ssid, sizeof(ssid));
    httpd_query_key_value(query, "password", password, sizeof(password));

    char *json;
    if (strlen(ssid) == 0) {
        json = web_ui_build_result_json("missing_ssid");
    } else {
        esp_err_t c = wifi_manager_connect(ssid, password);
        /* Persist regardless of immediate connect result; auto-reconnect
           will use the saved credentials. */
        config_manager_save_wifi(ssid, password);
        json = web_ui_build_result_json(c == ESP_OK ? "ok" : "connect_failed");
    }
    if (json == NULL) {
        return httpd_resp_send_500(req);
    }
    httpd_resp_set_type(req, "application/json");
    httpd_resp_send(req, json, (int)strlen(json));
    free(json);
    return ESP_OK;
}

static esp_err_t reset_handler(httpd_req_t *req)
{
    config_manager_factory_reset();
    httpd_resp_set_type(req, "application/json");
    httpd_resp_send(req, "{\"result\":\"ok\"}", 15);
    ESP_LOGI(TAG, "factory reset requested -> restarting");
    esp_restart();
    return ESP_OK;
}

esp_err_t web_server_start(void)
{
    if (s_server != NULL) {
        return ESP_OK;
    }
    httpd_config_t config = HTTPD_DEFAULT_CONFIG();
    config.stack_size = 8192;
    config.max_uri_handlers = 8;

    esp_err_t ret = httpd_start(&s_server, &config);
    if (ret != ESP_OK) {
        ESP_LOGE(TAG, "httpd_start failed: %s", esp_err_to_name(ret));
        return ret;
    }

    httpd_uri_t uris[] = {
        { .uri = "/",             .method = HTTP_GET, .handler = root_handler,   .user_ctx = NULL },
        { .uri = "/api/status",   .method = HTTP_GET, .handler = status_handler, .user_ctx = NULL },
        { .uri = "/api/scan",     .method = HTTP_GET, .handler = scan_handler,   .user_ctx = NULL },
        { .uri = "/api/connect",  .method = HTTP_GET, .handler = connect_handler, .user_ctx = NULL },
        { .uri = "/api/reset",    .method = HTTP_GET, .handler = reset_handler,  .user_ctx = NULL },
    };
    for (size_t i = 0; i < sizeof(uris) / sizeof(uris[0]); i++) {
        httpd_register_uri_handler(s_server, &uris[i]);
    }
    ESP_LOGI(TAG, "web server started");
    return ESP_OK;
}

void web_server_stop(void)
{
    if (s_server != NULL) {
        httpd_stop(s_server);
        s_server = NULL;
    }
}
