/**
  ******************************************************************************
  * @file    lv_font_cfg.h
  * @brief   Compile time choice of the CJK font engine.
  *
 *      LV_FONT_ENGINE_CTF (2, default)
 *          CTF index + the original .ttf.  A .ctf generated by
 *          tools/ttf2ctf/ttf2ctf.py maps code point -> glyf offset in three
 *          cached reads, so measuring a glyph never touches the TTF and a
 *          character the font lacks is rejected without any I/O at all.
 *          Latin falls back to the compiled-in Montserrat bitmaps, so English
 *          and digits survive a missing or unreadable index.
 *
 *      LV_FONT_ENGINE_HARMONYOS (1)
 *          The previous engine: HarmonyOS Sans TC outlines streamed straight
 *          off the card through LVGL's tiny_ttf.  Correct but slow - it looks
 *          every glyph up through cmap and asks stb for kerning LVGL never
 *          uses.  Kept for comparison.
 *
 *      LV_FONT_ENGINE_GBK (0)
 *          The original engine: fixed 1 bpp bitmaps read from
 *          1:/SYSTEM/FONT/GBKxx.FON.  Cheapest in RAM, no anti-aliasing, four
 *          fixed sizes.
 *
 *  How to switch
 *  -------------
 *    * edit the default below, or
 *    * build with  cmake -DLV_FONT_ENGINE=0 ..   (CMakeLists.txt forwards the
 *      value as a LV_FONT_ENGINE=<n> compile definition), or
 *    * add -DLV_FONT_ENGINE=0 to the compiler command line.
 *
 *  The GBK engine stays compiled in either way - it is the fallback when the
 *  card or the index is missing, and the font used by widgets that never had a
 *  style set.
 ******************************************************************************
 */
#ifndef __LV_FONT_CFG_H
#define __LV_FONT_CFG_H

#define LV_FONT_ENGINE_GBK          0
#define LV_FONT_ENGINE_HARMONYOS    1
#define LV_FONT_ENGINE_CTF          2

#ifndef LV_FONT_ENGINE
#define LV_FONT_ENGINE              LV_FONT_ENGINE_CTF
#endif

/* Catch a typo early rather than silently building the wrong engine. */
#if (LV_FONT_ENGINE != LV_FONT_ENGINE_GBK) && \
    (LV_FONT_ENGINE != LV_FONT_ENGINE_HARMONYOS) && \
    (LV_FONT_ENGINE != LV_FONT_ENGINE_CTF)
    #error "LV_FONT_ENGINE must be LV_FONT_ENGINE_GBK (0), LV_FONT_ENGINE_HARMONYOS (1) or LV_FONT_ENGINE_CTF (2)"
#endif

/* The CTF engine looks for its files here unless the board overrides it. */
#ifndef CTF_FONT_DIR
#define CTF_FONT_DIR   "1:/SYSTEM/HarmonyOS_Sans_SC"
#endif

#ifndef CTF_FONT_NAME
#define CTF_FONT_NAME  "HarmonyOS_Sans_SC_Regular"
#endif

#endif /* __LV_FONT_CFG_H */
