/******************************************************************************
 * @file    app/menu_icons.h
 * @brief   RGB565 icon descriptors for the root menu and the SD browser.
 *          Generated by tools/gen_menu_icons.py - do not edit by hand.
 ******************************************************************************/
#ifndef __MENU_ICONS_H
#define __MENU_ICONS_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

extern const lv_img_dsc_t icon_clock;
extern const lv_img_dsc_t icon_sysinfo;
extern const lv_img_dsc_t icon_keytest;
extern const lv_img_dsc_t icon_nes;
extern const lv_img_dsc_t icon_image;
extern const lv_img_dsc_t icon_about;
extern const lv_img_dsc_t icon_folder;
extern const lv_img_dsc_t icon_txt;

#ifdef __cplusplus
}
#endif

#endif /* __MENU_ICONS_H */
