#!/usr/bin/env python3
"""Convert PEM cert/key into a C header with static string literals.

Usage: python gen_tls_creds.py <cert.pem> <key.pem> <output.h>
"""
import sys


def pem_lines(path):
    with open(path, "r", encoding="utf-8") as f:
        s = f.read()
    out = []
    for line in s.splitlines():
        esc = line.replace(chr(92), chr(92) * 2).replace('"', chr(92) + '"')
        out.append('    "' + esc + '\\n"')
    return out


def main():
    cert_pem, key_pem, out_h = sys.argv[1:4]
    cert = pem_lines(cert_pem)
    key = pem_lines(key_pem)
    with open(out_h, "w", encoding="utf-8") as f:
        f.write("/*\n")
        f.write(" * tls_creds.h - self-signed EC P-256 credentials, generated by scripts/gen_tls_creds.py\n")
        f.write(" * DO NOT EDIT BY HAND. Regenerate:\n")
        f.write(" *   openssl ecparam -genkey -name prime256v1 -noout -out app/web/cert/tls_key.pem\n")
        f.write(" *   openssl req -new -x509 -key app/web/cert/tls_key.pem -out app/web/cert/tls_cert.pem \\\n")
        f.write(' *     -days 3650 -sha256 -subj "/CN=stm32f429.local/O=STM32F429 Net/OU=Embedded"\n')
        f.write(" */\n")
        f.write("#ifndef TLS_CREDS_H_\n#define TLS_CREDS_H_\n\n")
        f.write("static const char tls_cert_pem[] =\n")
        f.write("\n".join(cert))
        f.write(";\n\n")
        f.write("static const char tls_key_pem[] =\n")
        f.write("\n".join(key))
        f.write(";\n\n")
        f.write("#endif /* TLS_CREDS_H_ */\n")
    print("generated %s (%d lines cert, %d lines key)" % (out_h, len(cert), len(key)))


if __name__ == "__main__":
    main()
