/* AUTO-GENERATED by tools/gen_icons.py -- do not edit by hand. */
#pragma once

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

/* White ARGB8888 glyphs; tint them with lv_obj_set_style_image_recolor(). */
extern const lv_image_dsc_t icon_reader;
extern const lv_image_dsc_t icon_photos;
extern const lv_image_dsc_t icon_notes;
extern const lv_image_dsc_t icon_weather;
extern const lv_image_dsc_t icon_clock;
extern const lv_image_dsc_t icon_calendar;
extern const lv_image_dsc_t icon_drawing;
extern const lv_image_dsc_t icon_files;
extern const lv_image_dsc_t icon_file;
extern const lv_image_dsc_t icon_settings;
extern const lv_image_dsc_t icon_back;
extern const lv_image_dsc_t icon_forward;
extern const lv_image_dsc_t icon_up;
extern const lv_image_dsc_t icon_down;
extern const lv_image_dsc_t icon_plus;
extern const lv_image_dsc_t icon_minus;
extern const lv_image_dsc_t icon_close;
extern const lv_image_dsc_t icon_save;
extern const lv_image_dsc_t icon_trash;
extern const lv_image_dsc_t icon_refresh;

#ifdef __cplusplus
}
#endif

