/* AUTO-GENERATED by tools/gen_test_pattern.py -- do not edit by hand. */
#pragma once

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

/* 96x72 RGB565 LCD bring-up test pattern (colour bars + aspect square). */
extern const lv_image_dsc_t test_pattern;

#ifdef __cplusplus
}
#endif
