#!/usr/bin/env python3
"""Generate app/web/web_assets.c + .h from web/dist (Vue build output).

Scans web/dist for index.html and assets/*.css / assets/*.js, emits const
unsigned char arrays plus a web_asset_t lookup table keyed by URL path
(/index.html, /assets/<file>). Run after `npm run build`.
"""
import os
import re

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DIST = os.path.join(BASE, "web", "dist")
OUT_C = os.path.join(BASE, "app", "web", "web_assets.c")
OUT_H = os.path.join(BASE, "app", "web", "web_assets.h")

EXT_CTYPE = {
    ".html": "text/html; charset=utf-8",
    ".css": "text/css; charset=utf-8",
    ".js": "application/javascript",
    ".json": "application/json",
    ".ico": "image/x-icon",
    ".png": "image/png",
}


def sym_for(url):
    s = url.replace("/", "_").replace(".", "_").replace("-", "_")
    return "web_" + s


def emit_array(f, sym, raw):
    f.write("/* %d bytes */\n" % len(raw))
    f.write("static const unsigned char %s[] = {\n" % sym)
    for i in range(0, len(raw), 16):
        chunk = raw[i : i + 16]
        f.write("  " + ",".join("0x%02X" % b for b in chunk) + ",\n")
    f.write("};\n\n")


def main():
    if not os.path.isdir(DIST):
        raise SystemExit("dist not found: %s (run `npm run build` first)" % DIST)

    assets_dir = os.path.join(DIST, "assets")
    items = []  # (url, filepath, ctype)

    # index.html
    ih = os.path.join(DIST, "index.html")
    if os.path.isfile(ih):
        items.append(("/index.html", ih, "text/html; charset=utf-8"))

    # assets css + js
    if os.path.isdir(assets_dir):
        for fn in sorted(os.listdir(assets_dir)):
            full = os.path.join(assets_dir, fn)
            ext = os.path.splitext(fn)[1].lower()
            if ext in EXT_CTYPE and ext != ".html":
                items.append(("/assets/" + fn, full, EXT_CTYPE[ext]))

    if not items:
        raise SystemExit("no assets found in dist")

    syms = []
    with open(OUT_C, "w", newline="\n") as f:
        f.write("/* Auto-generated by scripts/gen_web_assets.py. DO NOT EDIT. */\n")
        f.write('#include "web_assets.h"\n\n')
        for url, fp, ctype in items:
            with open(fp, "rb") as fh:
                raw = fh.read()
            sym = sym_for(url)
            emit_array(f, sym, raw)
            syms.append((url, sym, len(raw), ctype))

        f.write("const web_asset_t web_assets[] = {\n")
        for url, sym, ln, ct in syms:
            f.write('  {"%s", %s, %d, "%s"},\n' % (url, sym, ln, ct))
        f.write("};\n\n")
        f.write("const int web_assets_count = %d;\n" % len(syms))

    with open(OUT_H, "w", newline="\n") as f:
        f.write("/* Auto-generated by scripts/gen_web_assets.py. DO NOT EDIT. */\n")
        f.write("#ifndef WEB_ASSETS_H\n#define WEB_ASSETS_H\n\n")
        f.write("#include <stdint.h>\n#include <stddef.h>\n\n")
        f.write(
            "typedef struct { const char *path; const uint8_t *data; size_t len; const char *ctype; } web_asset_t;\n\n"
        )
        f.write("extern const web_asset_t web_assets[];\n")
        f.write("extern const int web_assets_count;\n\n")
        f.write("#endif /* WEB_ASSETS_H */\n")

    total = sum(s[2] for s in syms)
    print("generated %d assets, total %d bytes:" % (len(syms), total))
    for url, sym, ln, ct in syms:
        print("  %-40s %6d B  %s" % (url, ln, ct))


if __name__ == "__main__":
    main()
