/**
 * @file    fd_model_data.h
 * @brief   GENERATED by tools/fd_export.py - do not edit.
 *
 * quantised from fd_float.weights.h5
 */
#ifndef __FD_MODEL_DATA_H
#define __FD_MODEL_DATA_H

#ifdef __cplusplus
extern "C" {
#endif

#include "fd_infer.h"

#define FD_NUM_BACKBONE   13u
#define FD_NUM_HEADS      3u
#define FD_ARENA_HALF     36864

/* Head output dequantisation: real = (q - ZP) * SCALE */
#define FD_HM_SCALE     0.03056257285f
#define FD_HM_ZP        (87)
#define FD_WH_SCALE     0.002180505442f
#define FD_WH_ZP        (-124)
#define FD_OFF_SCALE     0.005128293762f
#define FD_OFF_ZP        (-119)

extern const fd_layer_t fd_backbone[FD_NUM_BACKBONE];
extern const fd_layer_t fd_heads[FD_NUM_HEADS];

#ifdef __cplusplus
}
#endif
#endif /* __FD_MODEL_DATA_H */
