/* ascii_fonts.h - GENERATED by tools/gen_ascii_font.py. Do not edit. */
#pragma once
#include <stdint.h>
namespace ui {
extern const uint8_t ascii16_glyphs[];
extern const uint8_t ascii24_glyphs[];
extern const uint8_t ascii32_glyphs[];
}  // namespace ui
