/* Generated by tools/gen_gbk_table.py - do not edit by hand. */
#ifndef GBK_UNICODE_TBL_H
#define GBK_UNICODE_TBL_H

#include <stdint.h>

#define GBK_TBL_SIZE  23940
#define GBK_LEAD_MIN 0x81
#define GBK_LEAD_MAX 0xFE
#define GBK_COLS     190

extern const uint16_t gbk_to_unicode[GBK_TBL_SIZE];

#endif /* GBK_UNICODE_TBL_H */
