#!/usr/bin/env python3
"""
verify_framebuffer.py - end-to-end check of the emWin OLED panel over SWD.

Why this exists
---------------
The ST7789 is wired to SPI6 as a half-duplex, TX-only panel: there is no MISO,
so pixels cannot be read back from the controller.  What we *can* read is the
emWin framebuffer, which lives in plain AXI-SRAM:

    static uint16_t gui_vram[240 * 240];     /* Bsp/emWin/LCDConf.c */

If OLED_CopyBuffer() faithfully streams gui_vram to the panel (it is the only
path to the panel), then a pixel-exact assessment of gui_vram IS an assessment
of what is on the glass.  That is what this script checks - it needs only
OpenOCD + ST-Link, no serial console.

Gotchas baked in
----------------
1. gui_vram's address moves whenever the binary changes, so it is resolved from
   the ELF on every run.  Dumping a stale address produces a *fake* picture
   defect: an address 32 bytes too early shifts every pixel by +16 and puts
   neighbouring variables in the first 16 pixels of row 0.
2. emWin's GUICC_M565 conversion ROUNDS TO NEAREST, i.e. (v*31+127)/255 for
   5-bit fields (63 for the 6-bit green), NOT v>>3.  Truncating here makes
   perfectly good colours look 1 LSB wrong.
3. This OpenOCD build (Sysprogs 0.12.0) prints nothing for `mdw` inside a
   script, so nothing here depends on script-side printing.

Usage
-----
    python tools/verify_framebuffer.py                     # dump + verify
    python tools/verify_framebuffer.py --no-dump           # reuse last dump
    python tools/verify_framebuffer.py --dump-file x.bin --no-dump
    python tools/verify_framebuffer.py --elf build-rel/emwin_oled.elf
"""
from __future__ import annotations

import argparse
import os
import struct
import subprocess
import sys
import shutil
from collections import Counter

W = H = 240
FRAME_BYTES = W * H * 2


# --------------------------------------------------------------------------- #
# helpers
# --------------------------------------------------------------------------- #
def rgb565(r: int, g: int, b: int) -> int:
    """8-bit RGB -> RGB565 the way emWin's GUICC_M565 does it (round to nearest)."""
    return (((r * 31 + 127) // 255) << 11) | (((g * 63 + 127) // 255) << 5) \
         | ((b * 31 + 127) // 255)


def ui_col(c: int) -> int:
    """Application/app_ui.c::ui_col() - GUI_COLOR is 0x00BBGGRR, literals are 0x00RRGGBB."""
    return ((c & 0xFF) << 16) | (c & 0xFF00) | ((c >> 16) & 0xFF)


def palette() -> dict[str, int]:
    """Every colour app_ui.c can put on screen, as it lands in gui_vram."""
    literals = {
        "COL_BG": 0x000000, "COL_HDR": 0x0A3D62, "COL_HDR_TXT": 0xFFD966,
        "COL_CLOCK": 0x00E5FF, "COL_DATE": 0xFFFFFF, "COL_LABEL": 0x8A8A8A,
        "COL_VALUE": 0x40E070, "COL_ACCENT": 0xFFA000, "COL_BAR_BG": 0x2A2A2A,
        "COL_SEP": 0x243447, "COL_DIM": 0x606060, "COL_ERR": 0xFF4040,
        "COL_FAULT_HDR": 0x7A1010, "COL_FAULT_CY": 0x80D0FF, "COL_FAULT_GR": 0xB0B0B0,
    }
    out = {}
    for name, lit in literals.items():
        v = ui_col(lit)
        out[name] = rgb565(v & 0xFF, (v >> 8) & 0xFF, (v >> 16) & 0xFF)
    return out


def find_tool(name: str) -> str:
    p = shutil.which(name)
    if p:
        return p
    for root in (r"E:/support_tools/arm-gnu-toolchain-15.3.rel1-mingw-w64-x86_64-arm-none-eabi/bin",
                 r"C:/Software/arm-gnu-toolchain-14.2.rel1/bin"):
        cand = os.path.join(root, name + ".exe")
        if os.path.exists(cand):
            return cand
    raise SystemExit(f"required tool not found on PATH: {name}")


def resolve_symbol(elf: str, symbol: str) -> tuple[int, int]:
    """Return (address, size) of a symbol, via nm -S."""
    nm = find_tool("arm-none-eabi-nm")
    txt = subprocess.run([nm, "-S", elf], capture_output=True, text=True).stdout
    for line in txt.splitlines():
        parts = line.split()
        if len(parts) >= 3 and parts[-1] == symbol:
            return int(parts[0], 16), int(parts[1], 16)
    raise SystemExit(f"symbol {symbol} not found in {elf}")


def dump_frame(openocd: str, cfg: str, addr: int, size: int, out: str) -> None:
    script = os.path.join(os.path.dirname(out), "_dump_vram.cfg")
    with open(script, "w", encoding="ascii", newline="\n") as fh:
        fh.write(
            "# generated by tools/verify_framebuffer.py - do not edit\n"
            "init\n"
            "halt\n"
            f"dump_image {out} 0x{addr:08X} 0x{size:X}\n"
            "resume\n"
            "shutdown\n"
        )
    print(f"  openocd: dumping {size} bytes from 0x{addr:08X} -> {out}")
    r = subprocess.run([openocd, "-f", cfg, "-f", script],
                       capture_output=True, text=True)
    log = (r.stdout or "") + (r.stderr or "")
    if "dump_image" in log and "error" in log.lower():
        print(log)
        raise SystemExit("openocd dump failed")


# --------------------------------------------------------------------------- #
# checks
# --------------------------------------------------------------------------- #
class Report:
    def __init__(self) -> None:
        self.passed = 0
        self.failed: list[str] = []

    def check(self, name: str, ok: bool, detail: str = "") -> bool:
        print(f"  {'PASS' if ok else 'FAIL'}  {name}" + (f"   {detail}" if detail else ""))
        if ok:
            self.passed += 1
        else:
            self.failed.append(name)
        return ok


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--elf", default="build/emwin_oled.elf")
    ap.add_argument("--cfg", default="openocd.cfg")
    ap.add_argument("--symbol", default="gui_vram")
    ap.add_argument("--dump-file", default="build/vram.bin",
                    help="scratch capture (default build/, which is gitignored)")
    ap.add_argument("--no-dump", action="store_true",
                    help="skip OpenOCD and analyse --dump-file as-is")
    ap.add_argument("--expect", choices=("auto", "fault", "panel"), default="auto")
    args = ap.parse_args()

    if not args.no_dump:
        print("=== 0. resolve gui_vram and dump the framebuffer over SWD ===")
        addr, size = resolve_symbol(args.elf, args.symbol)
        print(f"  {args.symbol} = 0x{addr:08X}  size 0x{size:X} ({size} bytes)")
        if size < FRAME_BYTES:
            raise SystemExit(f"{args.symbol} is smaller than 240x240x2 ({FRAME_BYTES})")
        os.makedirs(os.path.dirname(args.dump_file) or ".", exist_ok=True)
        dump_frame(find_tool("openocd"), args.cfg, addr, FRAME_BYTES, args.dump_file)

    raw = open(args.dump_file, "rb").read()
    if len(raw) != FRAME_BYTES:
        print(f"FAIL: {args.dump_file} is {len(raw)} bytes, expected {FRAME_BYTES}")
        return 1
    px = struct.unpack("<%dH" % (W * H), raw)

    def row(y: int) -> tuple:
        return px[y * W:(y + 1) * W]

    hist = Counter(px)
    pal = palette()
    pal_by_val = {v: k for k, v in pal.items()}

    rep = Report()
    print("\n=== 1. something was drawn ===")
    nonbg = sum(n for v, n in hist.items() if v != hist.most_common(1)[0][0])
    rep.check("frame is not blank", len(hist) >= 2 and nonbg > 1000,
              f"{len(hist)} colours, {nonbg} non-background px")

    print("\n=== 2. every colour is a palette colour (M565 round-to-nearest) ===")
    unknown = {v: n for v, n in hist.items() if v not in pal_by_val}
    rep.check("no unexpected colours", not unknown,
              ", ".join(f"0x{v:04X}x{n}" for v, n in unknown.items()) or
              "all in palette")

    # Which page is on screen?  The bold fault-page header is unmistakable.
    fault_hdr = pal["COL_FAULT_HDR"]
    panel_hdr = pal["COL_HDR"]
    header_val = fault_hdr if hist.get(fault_hdr, 0) > 1000 else panel_hdr
    page = "fault" if header_val == fault_hdr else "panel"
    if args.expect != "auto" and args.expect != page:
        rep.check(f"expected the {args.expect} page", False, f"got the {page} page")
    else:
        rep.check(f"page identified: {page}", True,
                  f"header 0x{header_val:04X} x{hist.get(header_val, 0)}")

    print("\n=== 3. header band FillRect(0,0,239,27) ===")
    for y in (0, 3, 26, 27):
        n = sum(1 for v in row(y) if v == header_val)
        rep.check(f"y={y:2d} mostly the header colour", n >= 180, f"{n}/240 px")
    rep.check("band stops exactly at y=27", header_val not in row(28),
              "row 28 has no header-colour pixel")

    print("\n=== 4. text cursor advances (the bug that hid the whole UI) ===")
    # A callback font must move GUI_pContext->DispPosX itself; if it does not,
    # every glyph of a string piles up on one x and every "text" row is ~1 glyph
    # wide.  So: every row that has text must be much wider than a single glyph.
    text_widths = []
    for y in range(30, H):
        xs = [x for x, v in enumerate(row(y)) if v not in (0,)]
        if len(xs) > 6:
            text_widths.append((y, xs[0], xs[-1], xs[-1] - xs[0] + 1))
    if not text_widths:
        rep.check("found text rows", False, "no row with >6 lit pixels below y=30")
    else:
        worst = min(text_widths, key=lambda t: t[3])
        rep.check("found text rows", True, f"{len(text_widths)} rows")
        # 12px font ASCII advance is 9 px, 16px font is 9 px -> >60 px means
        # at least ~7 glyphs really advanced.
        rep.check("widest-row span > 60 px (no glyph pile-up)",
                  max(t[3] for t in text_widths) > 60,
                  f"widest {max(t[3] for t in text_widths)} px")
        rep.check("no row collapsed to a single glyph width",
                  worst[3] > 20,
                  f"narrowest y={worst[0]} x{worst[1]}..{worst[2]} ({worst[3]} px)")

    print("\n=== 5. frame summary ===")
    for v, n in hist.most_common(8):
        print(f"    0x{v:04X} x{n:6d}  {pal_by_val.get(v, '?')}")

    print(f"\n=== RESULT: {rep.passed} passed, {len(rep.failed)} failed ===")
    for f in rep.failed:
        print("  - " + f)
    return 1 if rep.failed else 0


if __name__ == "__main__":
    sys.exit(main())
