/*
 * tls_creds.h - self-signed EC P-256 credentials, generated by scripts/gen_tls_creds.py
 * DO NOT EDIT BY HAND. Regenerate:
 *   openssl ecparam -genkey -name prime256v1 -noout -out app/web/cert/tls_key.pem
 *   openssl req -new -x509 -key app/web/cert/tls_key.pem -out app/web/cert/tls_cert.pem \
 *     -days 3650 -sha256 -subj "/CN=stm32f429.local/O=STM32F429 Net/OU=Embedded"
 */
#ifndef TLS_CREDS_H_
#define TLS_CREDS_H_

static const char tls_cert_pem[] =
    "-----BEGIN CERTIFICATE-----\n"
    "MIIB3zCCAYWgAwIBAgIUL8wgwmhJDY5UYre94cGuSTPndqcwCgYIKoZIzj0EAwIw\n"
    "RTEYMBYGA1UEAwwPc3RtMzJmNDI5LmxvY2FsMRYwFAYDVQQKDA1TVE0zMkY0Mjkg\n"
    "TmV0MREwDwYDVQQLDAhFbWJlZGRlZDAeFw0yNjA4MjIwNTM0MjVaFw0zNjA4MTkw\n"
    "NTM0MjVaMEUxGDAWBgNVBAMMD3N0bTMyZjQyOS5sb2NhbDEWMBQGA1UECgwNU1RN\n"
    "MzJGNDI5IE5ldDERMA8GA1UECwwIRW1iZWRkZWQwWTATBgcqhkjOPQIBBggqhkjO\n"
    "PQMBBwNCAATgJBdsp44pdvwnXDZ8o2LwTNTpcSabLSZspRq+6KyPLtcx75rjymNj\n"
    "jWB7spzA4OUsGpYZDOSGo6kwswNP8k0vo1MwUTAdBgNVHQ4EFgQUy0Q64t1zfqKW\n"
    "qJYpBu+J+k8KYFEwHwYDVR0jBBgwFoAUy0Q64t1zfqKWqJYpBu+J+k8KYFEwDwYD\n"
    "VR0TAQH/BAUwAwEB/zAKBggqhkjOPQQDAgNIADBFAiBFgTok3+/1jjomHWU06OFC\n"
    "mW62rz290Fc4gkekLI9+4wIhAMYSvYFvdFr6Exdq7Es9oMGXYiUTSSwqRqUJw0hy\n"
    "AhEk\n"
    "-----END CERTIFICATE-----\n";

static const char tls_key_pem[] =
    "-----BEGIN EC PRIVATE KEY-----\n"
    "MHcCAQEEIKBLw19bLGZQceM9YfbFKhlCuzNfe8zollAjt3LPmpBuoAoGCCqGSM49\n"
    "AwEHoUQDQgAE4CQXbKeOKXb8J1w2fKNi8EzU6XEmmy0mbKUavuisjy7XMe+a48pj\n"
    "Y41ge7KcwODlLBqWGQzkhqOpMLMDT/JNLw==\n"
    "-----END EC PRIVATE KEY-----\n";

#endif /* TLS_CREDS_H_ */
